# Generated by Django 5.2.15 on 2026-06-26 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='jméno')),
                ('email', models.EmailField(max_length=254, verbose_name='e-mail')),
                ('phone', models.CharField(blank=True, max_length=40, verbose_name='telefon')),
                ('message', models.TextField(verbose_name='zpráva')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='vytvořeno')),
                ('handled', models.BooleanField(default=False, verbose_name='vyřízeno')),
            ],
            options={
                'verbose_name': 'poptávka',
                'verbose_name_plural': 'poptávky',
                'ordering': ('-created_at', '-id'),
            },
        ),
    ]
