# Generated by Django 5.2.15 on 2026-06-10 17:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3, unique=True, verbose_name='kód')),
                ('name', models.CharField(max_length=64, verbose_name='název')),
                ('address', models.CharField(blank=True, max_length=256, verbose_name='adresa')),
                ('is_active', models.BooleanField(default=True, verbose_name='aktivní')),
            ],
            options={
                'verbose_name': 'pobočka',
                'verbose_name_plural': 'pobočky',
                'ordering': ('code',),
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='název')),
                ('ico', models.CharField(blank=True, max_length=8, verbose_name='IČO')),
                ('address', models.TextField(blank=True, verbose_name='adresa')),
                ('is_active', models.BooleanField(default=True, verbose_name='aktivní')),
            ],
            options={
                'verbose_name': 'dodavatel',
                'verbose_name_plural': 'dodavatelé',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='název')),
                ('ico', models.CharField(blank=True, max_length=8, verbose_name='IČO')),
                ('dic', models.CharField(blank=True, max_length=16, verbose_name='DIČ')),
                ('address', models.TextField(blank=True, verbose_name='adresa')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='e-mail')),
                ('phone', models.CharField(blank=True, max_length=32, verbose_name='telefon')),
                ('is_default_recipient', models.BooleanField(default=False, verbose_name='výchozí odběratel')),
                ('is_active', models.BooleanField(default=True, verbose_name='aktivní')),
            ],
            options={
                'verbose_name': 'odběratel',
                'verbose_name_plural': 'odběratelé',
                'ordering': ('name',),
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_default_recipient', True)), fields=('is_default_recipient',), name='one_default_customer')],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_cs', models.CharField(max_length=128, verbose_name='název')),
                ('kind', models.CharField(choices=[('raw_spice', 'surovina'), ('mixture', 'směs')], max_length=16, verbose_name='typ')),
                ('is_active', models.BooleanField(default=True, verbose_name='aktivní')),
                ('notes', models.TextField(blank=True, verbose_name='poznámky')),
            ],
            options={
                'verbose_name': 'produkt',
                'verbose_name_plural': 'produkty',
                'ordering': ('name_cs',),
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('name_cs',), name='unique_active_product_name')],
            },
        ),
        migrations.CreateModel(
            name='RecipeComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ratio', models.DecimalField(decimal_places=6, max_digits=7, verbose_name='podíl')),
                ('component_product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='used_in_recipes', to='inventory.product', verbose_name='surovina')),
                ('mixture_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_components', to='inventory.product', verbose_name='směs')),
            ],
            options={
                'verbose_name': 'složka receptury',
                'verbose_name_plural': 'složky receptury',
                'ordering': ('mixture_product__name_cs', 'component_product__name_cs'),
                'constraints': [models.UniqueConstraint(fields=('mixture_product', 'component_product'), name='unique_component_per_mixture'), models.CheckConstraint(condition=models.Q(('ratio__gt', 0), ('ratio__lte', 1)), name='recipe_ratio_in_range')],
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='množství (kg)')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stocks', to='inventory.branch', verbose_name='pobočka')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stocks', to='inventory.product', verbose_name='produkt')),
            ],
            options={
                'verbose_name': 'stav skladu',
                'verbose_name_plural': 'stavy skladu',
                'ordering': ('branch__code', 'product__name_cs'),
                'constraints': [models.UniqueConstraint(fields=('product', 'branch'), name='unique_stock_per_product_branch'), models.CheckConstraint(condition=models.Q(('quantity__gte', 0)), name='stock_non_negative')],
            },
        ),
    ]
