# Generated by Django 5.2.15 on 2026-06-11 12:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_seed_branches_and_ricany'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Movement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('prijem', 'příjem'), ('vydej', 'výdej')], max_length=16, verbose_name='druh pohybu')),
                ('date_issued', models.DateField(verbose_name='datum vystavení')),
                ('note', models.TextField(blank=True, verbose_name='poznámka')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='vytvořeno')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='inventory.branch', verbose_name='pobočka')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_movements', to=settings.AUTH_USER_MODEL, verbose_name='vytvořil')),
                ('dodavatel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='prijem_movements', to='inventory.supplier', verbose_name='dodavatel')),
                ('odberatel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vydej_movements', to='inventory.customer', verbose_name='odběratel')),
            ],
            options={
                'verbose_name': 'pohyb',
                'verbose_name_plural': 'pohyby',
                'ordering': ('-date_issued', '-id'),
            },
        ),
        migrations.CreateModel(
            name='MovementAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edited_at', models.DateTimeField(auto_now_add=True, verbose_name='upraveno')),
                ('reason', models.TextField(verbose_name='důvod úpravy')),
                ('target_kind', models.CharField(choices=[('movement', 'pohyb'), ('line', 'položka')], max_length=16, verbose_name='cíl změny')),
                ('line_id', models.BigIntegerField(blank=True, null=True, verbose_name='ID položky')),
                ('event', models.CharField(choices=[('field_changed', 'změna pole'), ('line_added', 'přidaná položka'), ('line_removed', 'odebraná položka')], max_length=24, verbose_name='událost')),
                ('field', models.CharField(blank=True, default='', max_length=64, verbose_name='pole')),
                ('old_value', models.TextField(blank=True, default='', verbose_name='původní hodnota')),
                ('new_value', models.TextField(blank=True, default='', verbose_name='nová hodnota')),
                ('edited_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movement_edits', to=settings.AUTH_USER_MODEL, verbose_name='upravil')),
                ('movement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_entries', to='inventory.movement', verbose_name='pohyb')),
            ],
            options={
                'verbose_name': 'záznam auditu',
                'verbose_name_plural': 'záznamy auditu',
                'ordering': ('movement_id', 'edited_at', 'id'),
            },
        ),
        migrations.CreateModel(
            name='MovementLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_kg', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='množství (kg)')),
                ('sarze', models.CharField(blank=True, max_length=64, verbose_name='šarže')),
                ('expiry', models.DateField(blank=True, null=True, verbose_name='expirace')),
                ('note', models.CharField(blank=True, max_length=256, verbose_name='poznámka')),
                ('movement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='inventory.movement', verbose_name='pohyb')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movement_lines', to='inventory.product', verbose_name='produkt')),
            ],
            options={
                'verbose_name': 'položka pohybu',
                'verbose_name_plural': 'položky pohybu',
                'ordering': ('movement_id', 'id'),
            },
        ),
        migrations.AddConstraint(
            model_name='movement',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('kind', 'vydej'), ('odberatel__isnull', False), ('dodavatel__isnull', True)), models.Q(('kind', 'prijem'), ('dodavatel__isnull', False), ('odberatel__isnull', True)), _connector='OR'), name='movement_counterparty_matches_kind'),
        ),
        migrations.AddConstraint(
            model_name='movementaudit',
            constraint=models.CheckConstraint(condition=models.Q(('reason', ''), _negated=True), name='movement_audit_reason_required'),
        ),
        migrations.AddConstraint(
            model_name='movementline',
            constraint=models.CheckConstraint(condition=models.Q(('quantity_kg__gt', 0)), name='movement_line_quantity_positive'),
        ),
    ]
