# Generated by Django 5.2.15 on 2026-06-11 17:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_movement_and_audit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DodaciList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_issued', models.DateField(verbose_name='datum vystavení')),
                ('year_issued', models.PositiveSmallIntegerField(verbose_name='rok vystavení')),
                ('counter', models.PositiveIntegerField(verbose_name='pořadí')),
                ('cislo', models.CharField(max_length=24, unique=True, verbose_name='číslo')),
                ('current_version', models.PositiveIntegerField(default=1, verbose_name='aktuální verze')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='vytvořeno')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dodaci_lists', to='inventory.branch', verbose_name='pobočka')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_dodaci_lists', to=settings.AUTH_USER_MODEL, verbose_name='vytvořil')),
                ('movement', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='dodaci_list', to='inventory.movement', verbose_name='pohyb')),
                ('odberatel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dodaci_lists', to='inventory.customer', verbose_name='odběratel')),
            ],
            options={
                'verbose_name': 'dodací list',
                'verbose_name_plural': 'dodací listy',
                'ordering': ('-date_issued', '-id'),
            },
        ),
        migrations.CreateModel(
            name='DodaciListEmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField(verbose_name='verze')),
                ('sent_at', models.DateTimeField(auto_now_add=True, verbose_name='odesláno v')),
                ('recipients', models.CharField(max_length=512, verbose_name='příjemci')),
                ('trigger_reason', models.TextField(verbose_name='důvod odeslání')),
                ('status', models.CharField(choices=[('sent', 'odesláno'), ('failed', 'selhalo')], max_length=16, verbose_name='stav')),
                ('error_message', models.TextField(blank=True, default='', verbose_name='chybová zpráva')),
                ('dodaci_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_logs', to='inventory.dodacilist', verbose_name='dodací list')),
            ],
            options={
                'verbose_name': 'záznam odeslání dodacího listu',
                'verbose_name_plural': 'záznamy odeslání dodacích listů',
                'ordering': ('dodaci_list_id', 'sent_at', 'id'),
            },
        ),
        migrations.CreateModel(
            name='DodaciListNumberSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField(verbose_name='rok')),
                ('last_counter', models.PositiveIntegerField(default=0, verbose_name='poslední pořadí')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='number_sequences', to='inventory.branch', verbose_name='pobočka')),
            ],
            options={
                'verbose_name': 'číselná řada dodacích listů',
                'verbose_name_plural': 'číselné řady dodacích listů',
                'ordering': ('branch__code', 'year'),
            },
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('singleton_key', models.CharField(default='singleton', editable=False, max_length=16)),
                ('company_name', models.CharField(default='Kasia vera s.r.o.', max_length=128, verbose_name='název firmy')),
                ('company_ico', models.CharField(default='25756729', max_length=16, verbose_name='IČO')),
                ('company_dic', models.CharField(blank=True, max_length=16, verbose_name='DIČ')),
                ('company_address', models.TextField(default='Říčany u Prahy', verbose_name='adresa')),
                ('company_phone', models.CharField(blank=True, max_length=32, verbose_name='telefon')),
                ('company_email', models.EmailField(blank=True, max_length=254, verbose_name='kontaktní e-mail')),
                ('logo', models.FileField(blank=True, upload_to='logos/', verbose_name='logo')),
                ('footer_text', models.TextField(blank=True, default='Kasia vera s.r.o. · IČO 25756729 · Říčany u Prahy', verbose_name='patička')),
                ('smtp_host', models.CharField(blank=True, max_length=128, verbose_name='SMTP server')),
                ('smtp_port', models.PositiveIntegerField(default=587, verbose_name='SMTP port')),
                ('smtp_use_tls', models.BooleanField(default=True, verbose_name='použít TLS')),
                ('smtp_user', models.CharField(blank=True, max_length=128, verbose_name='SMTP uživatel')),
                ('smtp_password', models.CharField(blank=True, max_length=128, verbose_name='SMTP heslo')),
                ('email_from_address', models.EmailField(blank=True, max_length=254, verbose_name='odesílatel — adresa')),
                ('email_from_name', models.CharField(blank=True, max_length=128, verbose_name='odesílatel — jméno')),
                ('recipient_petr', models.EmailField(blank=True, max_length=254, verbose_name='příjemce Petr')),
                ('recipient_karolina', models.EmailField(blank=True, max_length=254, verbose_name='příjemce Karolína')),
                ('template_initial_subject', models.CharField(default='Dodací list <číslo> — Kasia vera', max_length=256, verbose_name='předmět — nový dodák')),
                ('template_initial_body', models.TextField(default='Dobrý den, v příloze posíláme dodací list <číslo> ze dne <datum>. S pozdravem, Kasia vera s.r.o.', verbose_name='tělo — nový dodák')),
                ('template_oprava_subject', models.CharField(default='[OPRAVA] Dodací list <číslo> — Kasia vera', max_length=256, verbose_name='předmět — oprava')),
                ('template_oprava_body', models.TextField(default='Dobrý den, opravujeme dříve zaslaný dodací list <číslo>. Důvod: <text zdůvodnění od operátorky>. Nová verze v příloze nahrazuje předchozí. S pozdravem, Kasia vera s.r.o.', verbose_name='tělo — oprava')),
            ],
            options={
                'verbose_name': 'nastavení',
                'verbose_name_plural': 'nastavení',
                'constraints': [models.UniqueConstraint(fields=('singleton_key',), name='settings_singleton')],
            },
        ),
        migrations.AddConstraint(
            model_name='dodacilist',
            constraint=models.UniqueConstraint(fields=('branch', 'year_issued', 'counter'), name='unique_dodaci_list_branch_year_counter'),
        ),
        migrations.AddConstraint(
            model_name='dodacilist',
            constraint=models.CheckConstraint(condition=models.Q(('counter__gte', 1)), name='dodaci_list_counter_positive'),
        ),
        migrations.AddConstraint(
            model_name='dodacilist',
            constraint=models.CheckConstraint(condition=models.Q(('current_version__gte', 1)), name='dodaci_list_version_positive'),
        ),
        migrations.AddConstraint(
            model_name='dodacilistemaillog',
            constraint=models.CheckConstraint(condition=models.Q(('version__gte', 1)), name='email_log_version_positive'),
        ),
        migrations.AddConstraint(
            model_name='dodacilistnumbersequence',
            constraint=models.UniqueConstraint(fields=('branch', 'year'), name='unique_branch_year_sequence'),
        ),
    ]
