# Generated by Django 5.2.15 on 2026-06-12 09:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_seed_settings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='is_internal',
            field=models.BooleanField(default=False, help_text='Interní odběratele systém používá pro účetně-vnitřní pohyby (např. míchání směsí per 0039). Skrývají se v pickeru výdeje a vystavení dodacího listu se na ně přeskočí.', verbose_name='interní (míchárna apod.)'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='is_internal',
            field=models.BooleanField(default=False, help_text='Interní dodavatele systém používá pro účetně-vnitřní pohyby (např. míchání směsí per 0039). Skrývají se v pickeru příjmu.', verbose_name='interní (míchárna apod.)'),
        ),
        migrations.CreateModel(
            name='MixingJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_qty', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='cílové množství (kg)')),
                ('actual_produced_qty', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='skutečně vyrobeno (kg)')),
                ('state', models.CharField(choices=[('running', 'probíhá'), ('done', 'dokončeno'), ('cancelled', 'zrušeno')], default='running', max_length=16, verbose_name='stav')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='zahájeno')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='ukončeno')),
                ('cancel_reason', models.TextField(blank=True, default='', verbose_name='důvod zrušení')),
                ('note', models.TextField(blank=True, default='', verbose_name='poznámka')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mixing_jobs', to='inventory.branch', verbose_name='pobočka')),
                ('consume_movement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mixing_job_as_consume', to='inventory.movement', verbose_name='pohyb spotřeby')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_mixing_jobs', to=settings.AUTH_USER_MODEL, verbose_name='vytvořil')),
                ('mixture', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mixing_jobs', to='inventory.product', verbose_name='směs')),
                ('produce_movement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mixing_job_as_produce', to='inventory.movement', verbose_name='pohyb produkce')),
            ],
            options={
                'verbose_name': 'míchací dávka',
                'verbose_name_plural': 'míchací dávky',
                'ordering': ('-started_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='MixingJobLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ratio_at_start', models.DecimalField(decimal_places=6, max_digits=7, verbose_name='podíl při zahájení')),
                ('derived_qty', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='odvozené množství (kg)')),
                ('actual_qty', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='skutečné množství (kg)')),
                ('sarze', models.CharField(blank=True, max_length=64, verbose_name='šarže')),
                ('component_product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mixing_job_lines', to='inventory.product', verbose_name='surovina')),
                ('mixing_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='inventory.mixingjob', verbose_name='míchací dávka')),
            ],
            options={
                'verbose_name': 'položka míchání',
                'verbose_name_plural': 'položky míchání',
                'ordering': ('mixing_job_id', 'id'),
            },
        ),
        migrations.AddConstraint(
            model_name='mixingjob',
            constraint=models.CheckConstraint(condition=models.Q(('target_qty__gt', 0)), name='mixing_job_target_qty_positive'),
        ),
        migrations.AddConstraint(
            model_name='mixingjob',
            constraint=models.CheckConstraint(condition=models.Q(('actual_produced_qty__isnull', True), ('actual_produced_qty__gte', 0), _connector='OR'), name='mixing_job_actual_produced_qty_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='mixingjob',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('state', 'cancelled'), _negated=True), models.Q(('cancel_reason', ''), _negated=True), _connector='OR'), name='mixing_job_cancel_reason_required'),
        ),
        migrations.AddConstraint(
            model_name='mixingjobline',
            constraint=models.UniqueConstraint(fields=('mixing_job', 'component_product'), name='unique_mixing_job_component'),
        ),
        migrations.AddConstraint(
            model_name='mixingjobline',
            constraint=models.CheckConstraint(condition=models.Q(('derived_qty__gt', 0)), name='mixing_job_line_derived_positive'),
        ),
        migrations.AddConstraint(
            model_name='mixingjobline',
            constraint=models.CheckConstraint(condition=models.Q(('actual_qty__gt', 0)), name='mixing_job_line_actual_positive'),
        ),
    ]
