# Generated by Django 5.2.15 on 2026-06-14 11:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_seed_adjustment_counterparty'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='mixingjob',
            name='planned_for',
            field=models.DateField(blank=True, help_text='Pouze pro state=PLANNED — kdy operátor předpokládá fyzické míchání. Po přechodu na RUNNING už nemá smysl, pole zůstane jako historický záznam.', null=True, verbose_name='plánováno na'),
        ),
        migrations.AddField(
            model_name='product',
            name='reorder_threshold_kg',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Hranice, pod kterou se produkt objeví na panelu „Dochází zboží a v denním e-mailu Petrovi (per 0043). Prázdné = bez upozornění; 0 znamená alert při skutečně nulovém efektivním stavu.', max_digits=10, null=True, verbose_name='objednací bod (kg)'),
        ),
        migrations.AddField(
            model_name='settings',
            name='template_low_stock_body',
            field=models.TextField(default='Dobrý den, dnes je pod hranicí těchto produktů: <seznam>. S pozdravem, Kasia vera s.r.o.', verbose_name='tělo — dochází zboží'),
        ),
        migrations.AddField(
            model_name='settings',
            name='template_low_stock_subject',
            field=models.CharField(default='Dochází zboží — <datum>', max_length=256, verbose_name='předmět — dochází zboží'),
        ),
        migrations.AlterField(
            model_name='mixingjob',
            name='state',
            field=models.CharField(choices=[('planned', 'naplánováno'), ('running', 'probíhá'), ('done', 'dokončeno'), ('cancelled', 'zrušeno')], default='running', max_length=16, verbose_name='stav'),
        ),
        migrations.CreateModel(
            name='PlannedTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_kg', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='množství (kg)')),
                ('scheduled_for', models.DateField(verbose_name='plánováno na')),
                ('state', models.CharField(choices=[('planned', 'naplánováno'), ('done', 'provedeno'), ('cancelled', 'zrušeno')], default='planned', max_length=16, verbose_name='stav')),
                ('notes', models.TextField(blank=True, default='', verbose_name='poznámka')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='vytvořeno')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_planned_transfers', to=settings.AUTH_USER_MODEL, verbose_name='vytvořil')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='planned_transfers', to='inventory.product', verbose_name='produkt')),
                ('source_branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outgoing_planned_transfers', to='inventory.branch', verbose_name='zdrojová pobočka')),
                ('target_branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incoming_planned_transfers', to='inventory.branch', verbose_name='cílová pobočka')),
            ],
            options={
                'verbose_name': 'plánovaný převod',
                'verbose_name_plural': 'plánované převody',
                'ordering': ('-scheduled_for', '-id'),
            },
        ),
        migrations.AddField(
            model_name='movement',
            name='transfer',
            field=models.ForeignKey(blank=True, help_text='Set by `execute_planned_transfer` on both paired Movements (the výdej at source + the příjem at target) so the audit trail can link executed Movements back to their originating PlannedTransfer. NULL on every other Movement.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='inventory.plannedtransfer', verbose_name='plánovaný převod'),
        ),
        migrations.CreateModel(
            name='StockThresholdOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('threshold_kg', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='objednací bod (kg)')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='threshold_overrides', to='inventory.branch', verbose_name='pobočka')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='threshold_overrides', to='inventory.product', verbose_name='produkt')),
            ],
            options={
                'verbose_name': 'objednací bod (pobočka)',
                'verbose_name_plural': 'objednací body (pobočky)',
                'ordering': ('product__name_cs', 'branch__code'),
            },
        ),
        migrations.AddConstraint(
            model_name='plannedtransfer',
            constraint=models.CheckConstraint(condition=models.Q(('source_branch', models.F('target_branch')), _negated=True), name='planned_transfer_different_branches'),
        ),
        migrations.AddConstraint(
            model_name='plannedtransfer',
            constraint=models.CheckConstraint(condition=models.Q(('quantity_kg__gt', 0)), name='planned_transfer_qty_positive'),
        ),
        migrations.AddConstraint(
            model_name='stockthresholdoverride',
            constraint=models.UniqueConstraint(fields=('product', 'branch'), name='unique_threshold_override_per_product_branch'),
        ),
        migrations.AddConstraint(
            model_name='stockthresholdoverride',
            constraint=models.CheckConstraint(condition=models.Q(('threshold_kg__gte', 0)), name='threshold_override_nonneg'),
        ),
    ]
