# Generated by Django 5.2.15 on 2026-06-16 12:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_seed_transfer_counterparty'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='vytvořeno')),
                ('page_url', models.CharField(blank=True, max_length=255, verbose_name='stránka')),
                ('description', models.TextField(verbose_name='popis')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='vyřešeno v')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_feedback', to=settings.AUTH_USER_MODEL, verbose_name='autor')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_feedback', to=settings.AUTH_USER_MODEL, verbose_name='vyřešil')),
            ],
            options={
                'verbose_name': 'hlášení',
                'verbose_name_plural': 'hlášení',
                'ordering': ('-created_at',),
            },
        ),
    ]
