# Generated by Django 5.2.15 on 2026-06-30 21:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_seed_stock_for_existing_products'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlannedOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_kg', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='objednané množství (kg)')),
                ('received_qty', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='přijaté množství (kg)')),
                ('expected_on', models.DateField(verbose_name='očekávaný příjezd')),
                ('state', models.CharField(choices=[('planned', 'objednáno'), ('received', 'přijato'), ('cancelled', 'zrušeno')], default='planned', max_length=16, verbose_name='stav')),
                ('notes', models.TextField(blank=True, default='', verbose_name='poznámka')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='vytvořeno')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='planned_orders', to='inventory.branch', verbose_name='pobočka')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_planned_orders', to=settings.AUTH_USER_MODEL, verbose_name='vytvořil')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='planned_orders', to='inventory.product', verbose_name='produkt')),
                ('received_movement', models.ForeignKey(blank=True, help_text='Set by `receive_planned_order` on confirm — the one PRIJEM Movement that added the received kg to stock. NULL while the order is still PLANNED or was CANCELLED.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='from_planned_order', to='inventory.movement', verbose_name='příjem (přijetí)')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='planned_orders', to='inventory.supplier', verbose_name='dodavatel')),
            ],
            options={
                'verbose_name': 'objednávka',
                'verbose_name_plural': 'objednávky',
                'ordering': ('-expected_on', '-id'),
                'constraints': [models.CheckConstraint(condition=models.Q(('quantity_kg__gt', 0)), name='planned_order_qty_positive')],
            },
        ),
    ]
