# Generated by Django 5.2.15 on 2026-07-04 11:01
#
# Per decision 0072: reorder_threshold_kg becomes NOT NULL with a default of 0.
# Backfill existing NULLs → 0 BEFORE the AlterField — Postgres does not backfill
# from a column default when altering to NOT NULL.

from decimal import Decimal
from django.db import migrations, models


def backfill_null_thresholds(apps, schema_editor):
    Product = apps.get_model('inventory', 'Product')
    Product.objects.filter(reorder_threshold_kg__isnull=True).update(
        reorder_threshold_kg=Decimal('0.000')
    )


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0017_migrate_open_planned_orders'),
    ]

    operations = [
        migrations.RunPython(backfill_null_thresholds, noop),
        migrations.AlterField(
            model_name='product',
            name='reorder_threshold_kg',
            field=models.DecimalField(blank=True, decimal_places=3, default=Decimal('0.000'), help_text='Hranice, pod kterou se produkt objeví na panelu „Dochází zboží a v denním e-mailu Petrovi (per 0043/0072). Nové produkty mají výchozí 0; produkt s nulovým efektivním stavem se vždy zobrazí ve skupině „Prázdné“.', max_digits=10, verbose_name='objednací bod (kg)'),
        ),
    ]
