# Generated by Django 5.2.15 on 2026-07-14 16:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0019_email_log'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScreenVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_name', models.CharField(max_length=64, verbose_name='obrazovka')),
                ('namespace', models.CharField(blank=True, default='', max_length=32, verbose_name='jmenný prostor')),
                ('path', models.CharField(max_length=512, verbose_name='cesta')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='navštíveno')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='screen_visits', to=settings.AUTH_USER_MODEL, verbose_name='uživatel')),
            ],
            options={
                'verbose_name': 'návštěva obrazovky',
                'verbose_name_plural': 'návštěvy obrazovek',
                'ordering': ('-created_at', '-id'),
                'indexes': [models.Index(fields=['user', 'created_at'], name='inventory_s_user_id_6bcc6a_idx'), models.Index(fields=['url_name', 'created_at'], name='inventory_s_url_nam_3c6eac_idx')],
            },
        ),
    ]
