# Generated by Django 5.2.15 on 2026-07-21 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0020_screen_visit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emaillog',
            name='category',
            field=models.CharField(choices=[('dodaci_vystaveni', 'dodací list — vystavení'), ('dodaci_oprava', 'dodací list — oprava'), ('dodaci_resend', 'dodací list — opětovné odeslání'), ('low_stock_alert', 'upozornění — dochází zboží'), ('feedback', 'hlášení z podpory'), ('smtp_test', 'test SMTP')], max_length=32, verbose_name='kategorie'),
        ),
    ]
