# Generated by Django 5.2.15 on 2026-07-21 10:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0021_alter_emaillog_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='settingsrecipient',
            name='dodaci_branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dodaci_recipients', to='inventory.branch', verbose_name='pobočka (dodáky)'),
        ),
        migrations.AddField(
            model_name='settingsrecipient',
            name='is_dodaci_recipient',
            field=models.BooleanField(default=True, verbose_name='dostává dodací listy'),
        ),
        migrations.AddField(
            model_name='settingsrecipient',
            name='is_feedback_recipient',
            field=models.BooleanField(default=False, verbose_name='dostává hlášení z Podpory'),
        ),
        migrations.AlterField(
            model_name='emaillog',
            name='category',
            field=models.CharField(choices=[('dodaci_vystaveni', 'dodací list — vystavení'), ('dodaci_oprava', 'dodací list — oprava'), ('dodaci_resend', 'dodací list — opětovné odeslání'), ('low_stock_alert', 'upozornění — dochází zboží'), ('feedback', 'hlášení z podpory'), ('new_user_credentials', 'přihlašovací údaje nového uživatele'), ('smtp_test', 'test SMTP')], max_length=32, verbose_name='kategorie'),
        ),
    ]
