# Generated by Django 5.2.15 on 2026-07-21 15:14

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0024_seed_neuveden_supplier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='reorder_threshold_kg',
            field=models.DecimalField(blank=True, decimal_places=3, default=Decimal('0.000'), help_text='Hranice, pod kterou se produkt objeví na panelu „Dochází zboží a v denním e-mailu příjemcům upozornění „dochází zboží (per 0043/0072). Nové produkty mají výchozí 0; produkt s nulovým efektivním stavem se vždy zobrazí ve skupině „Prázdné“.', max_digits=10, verbose_name='objednací bod (kg)'),
        ),
    ]
