# Generated by Django 5.2.15 on 2026-07-22 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0025_alter_product_reorder_threshold_kg'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_stock_tracked',
            field=models.BooleanField(default=True, help_text='Odškrtnuté produkty (např. „Voda“) se skladově nesledují: nemají skladové řádky, nezobrazují se v Katalogu / Přehledu / inventuře, nikdy nejsou „Prázdné“/„Dochází“, neblokují výdej ani míchání a neposílají upozornění. Nastavuje se pouze při založení produktu (per 0088).', verbose_name='sledovat sklad'),
        ),
        migrations.AddField(
            model_name='recipecomponent',
            name='note',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='poznámka ke složce'),
        ),
    ]
