# Generated by Django 5.2.15 on 2026-07-22 11:12

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0026_product_is_stock_tracked_recipecomponent_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='default_batch_kg',
            field=models.DecimalField(blank=True, decimal_places=3, default=Decimal('0.000'), help_text='Výchozí velikost dávky, kterou systém předvyplní do míchání (pole „Cílové množství“) a do kalkulačky dávky na detailu produktu (per 0089). 0 = nenastaveno (chová se jako dřív). Má smysl jen u směsí.', max_digits=10, verbose_name='výchozí dávka (kg)'),
        ),
    ]
