# Generated by Django 5.2.15 on 2026-07-22 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0027_product_default_batch_kg'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipecomponent',
            options={'ordering': ('mixture_product__name_cs', 'position', 'id'), 'verbose_name': 'složka receptury', 'verbose_name_plural': 'složky receptury'},
        ),
        migrations.AddField(
            model_name='recipecomponent',
            name='position',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='pořadí'),
        ),
    ]
