# Generated by Django 5.2.15 on 2026-07-23 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0028_alter_recipecomponent_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='kind',
            field=models.CharField(choices=[('raw_spice', 'surovina'), ('mixture', 'směs'), ('hotovy_vyrobek', 'hotový výrobek')], max_length=16, verbose_name='typ'),
        ),
    ]
