# Generated by Django 5.2.15 on 2026-07-23 11:23
#
# Per decision 0096 (manual first-send of dodáky): the new send_state gates the
# first e-mail. New rows default to WAITING, but every *pre-existing* dodák was
# already auto-issued under the old flow, so it must read SENT — otherwise the
# whole back-catalogue would resurface in the new "Čeká na odeslání" lists.
# Prod has 0 dodáky (0087 wipe) so this is a no-op there; it only matters for
# dev/test snapshots.

from django.db import migrations, models


def _backfill_existing_sent(apps, schema_editor):
    apps.get_model("inventory", "DodaciList").objects.update(send_state="sent")


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0029_alter_product_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='dodacilist',
            name='send_state',
            field=models.CharField(choices=[('waiting', 'čeká na odeslání'), ('sent', 'odesláno')], default='waiting', max_length=16, verbose_name='stav odeslání'),
        ),
        migrations.RunPython(_backfill_existing_sent, migrations.RunPython.noop, elidable=False),
    ]
