# Generated by Django 5.2.15 on 2026-07-23 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0030_dodacilist_send_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='resolution_note',
            field=models.TextField(blank=True, verbose_name='poznámka k vyřešení'),
        ),
        migrations.AlterField(
            model_name='emaillog',
            name='category',
            field=models.CharField(choices=[('dodaci_vystaveni', 'dodací list — vystavení'), ('dodaci_oprava', 'dodací list — oprava'), ('dodaci_resend', 'dodací list — opětovné odeslání'), ('low_stock_alert', 'upozornění — dochází zboží'), ('feedback', 'hlášení z podpory'), ('feedback_resolved', 'vyřešené hlášení'), ('announcement', 'oznámení'), ('new_user_credentials', 'přihlašovací údaje nového uživatele'), ('password_reset', 'reset hesla'), ('smtp_test', 'test SMTP')], max_length=32, verbose_name='kategorie'),
        ),
        migrations.AlterField(
            model_name='emaillog',
            name='recipients',
            field=models.TextField(verbose_name='příjemci'),
        ),
    ]
