# Generated by Django 5.2.15 on 2026-07-26 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0031_feedback_resolution_note_alter_emaillog_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emaillog',
            name='category',
            field=models.CharField(choices=[('dodaci_vystaveni', 'dodací list — vystavení'), ('dodaci_oprava', 'dodací list — oprava'), ('dodaci_resend', 'dodací list — opětovné odeslání'), ('vydej_request', 'žádost o vyřízení výdeje'), ('low_stock_alert', 'upozornění — dochází zboží'), ('feedback', 'hlášení z podpory'), ('feedback_resolved', 'vyřešené hlášení'), ('announcement', 'oznámení'), ('new_user_credentials', 'přihlašovací údaje nového uživatele'), ('password_reset', 'reset hesla'), ('smtp_test', 'test SMTP')], max_length=32, verbose_name='kategorie'),
        ),
    ]
