# Generated by Django 5.2.15 on 2026-09-30 09:02
# Per decision 0103: Customer.email (single, never read) -> Customer.emails
# (JSON list, receives every dodák). Existing values are dropped — no data copy.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0032_alter_emaillog_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='email',
        ),
        migrations.AddField(
            model_name='customer',
            name='emails',
            field=models.JSONField(blank=True, default=list, verbose_name='kontaktní e-maily'),
        ),
    ]
